# Generated by Django 4.2.5 on 2023-09-29 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop3_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attn_number', models.CharField(max_length=20)),
                ('seat_number', models.CharField(max_length=4)),
                ('show_time', models.CharField(max_length=15)),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop3_app.movie')),
            ],
            options={
                'ordering': ['attn_number'],
            },
        ),
    ]
