# Generated by Django 4.2.5 on 2023-09-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop3_app', '0002_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='attend_info',
            field=models.BooleanField(default=False),
        ),
    ]
