# Generated by Django 4.2.5 on 2023-09-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop3_app', '0003_attend_attend_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='movie_name',
            field=models.CharField(max_length=200),
        ),
    ]
